// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/session-message.proto

package org.alan.mars.cluster.pb;

public final class SessionMessage {
  private SessionMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AddressOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string host = 1;
    /**
     * <code>required string host = 1;</code>
     */
    boolean hasHost();
    /**
     * <code>required string host = 1;</code>
     */
    java.lang.String getHost();
    /**
     * <code>required string host = 1;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    // required fixed32 port = 2;
    /**
     * <code>required fixed32 port = 2;</code>
     */
    boolean hasPort();
    /**
     * <code>required fixed32 port = 2;</code>
     */
    int getPort();
  }
  /**
   * Protobuf type {@code com.tsixi.mars.cluster.pb.Address}
   *
   * <pre>
   **
   * 基础PB协议配置文件，协议格式如下
   *	
   * message_type 指定消息类型，便于消息分类，后续消息定义时应该将不同的消息大类分布到不同的文件中
   * cmd 消息命令字，基于消息大类后的子消息命令字，使用可选字段，在没有时可以不使用
   * data_message 具体消息序列，将具体的消息转成序列后设置到基础消息中进行传送
   *
   * 考虑在本文件中进行消息的完整描述，与方便程序中进行消息分类与处理，我们在每个具体消息结构中包含消息的分类与命令字，使用默认值的
   * 方式提前设置在消息中，后续在程序中不用去设置他，这样在pb进行编码压缩处理后不会增加额外的字节。
   * 
   *
   * message_type 消息分类1-100数字留做底层使用，上层消息分类使用100以后数字
   * cmd 命令字1-100数字留做底层使用，上层消息命令字请从100以后开始
   *
   * protoc --java_out=./src/main/java base-message.proto
   * getMessageType
   * </pre>
   */
  public static final class Address extends
      com.google.protobuf.GeneratedMessage
      implements AddressOrBuilder {
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Address(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Address defaultInstance;
    public static Address getDefaultInstance() {
      return defaultInstance;
    }

    public Address getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Address(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              host_ = input.readBytes();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              port_ = input.readFixed32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_Address_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SessionMessage.Address.class, SessionMessage.Address.Builder.class);
    }

    public static com.google.protobuf.Parser<Address> PARSER =
        new com.google.protobuf.AbstractParser<Address>() {
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Address(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string host = 1;
    public static final int HOST_FIELD_NUMBER = 1;
    private java.lang.Object host_;
    /**
     * <code>required string host = 1;</code>
     */
    public boolean hasHost() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string host = 1;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          host_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string host = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required fixed32 port = 2;
    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>required fixed32 port = 2;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required fixed32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }

    private void initFields() {
      host_ = "";
      port_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHost()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getHostBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed32(2, port_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getHostBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, port_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SessionMessage.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SessionMessage.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SessionMessage.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SessionMessage.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SessionMessage.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SessionMessage.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SessionMessage.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SessionMessage.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SessionMessage.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SessionMessage.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SessionMessage.Address prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tsixi.mars.cluster.pb.Address}
     *
     * <pre>
     **
     * 基础PB协议配置文件，协议格式如下
     *	
     * message_type 指定消息类型，便于消息分类，后续消息定义时应该将不同的消息大类分布到不同的文件中
     * cmd 消息命令字，基于消息大类后的子消息命令字，使用可选字段，在没有时可以不使用
     * data_message 具体消息序列，将具体的消息转成序列后设置到基础消息中进行传送
     *
     * 考虑在本文件中进行消息的完整描述，与方便程序中进行消息分类与处理，我们在每个具体消息结构中包含消息的分类与命令字，使用默认值的
     * 方式提前设置在消息中，后续在程序中不用去设置他，这样在pb进行编码压缩处理后不会增加额外的字节。
     * 
     *
     * message_type 消息分类1-100数字留做底层使用，上层消息分类使用100以后数字
     * cmd 命令字1-100数字留做底层使用，上层消息命令字请从100以后开始
     *
     * protoc --java_out=./src/main/java base-message.proto
     * getMessageType
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SessionMessage.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_Address_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SessionMessage.Address.class, SessionMessage.Address.Builder.class);
      }

      // Construct using SessionMessage.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        host_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_Address_descriptor;
      }

      public SessionMessage.Address getDefaultInstanceForType() {
        return SessionMessage.Address.getDefaultInstance();
      }

      public SessionMessage.Address build() {
        SessionMessage.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SessionMessage.Address buildPartial() {
        SessionMessage.Address result = new SessionMessage.Address(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.host_ = host_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.port_ = port_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SessionMessage.Address) {
          return mergeFrom((SessionMessage.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SessionMessage.Address other) {
        if (other == SessionMessage.Address.getDefaultInstance()) return this;
        if (other.hasHost()) {
          bitField0_ |= 0x00000001;
          host_ = other.host_;
          onChanged();
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHost()) {
          
          return false;
        }
        if (!hasPort()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SessionMessage.Address parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SessionMessage.Address) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string host = 1;
      private java.lang.Object host_ = "";
      /**
       * <code>required string host = 1;</code>
       */
      public boolean hasHost() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string host = 1;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string host = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string host = 1;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 1;</code>
       */
      public Builder clearHost() {
        bitField0_ = (bitField0_ & ~0x00000001);
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>required string host = 1;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        host_ = value;
        onChanged();
        return this;
      }

      // required fixed32 port = 2;
      private int port_ ;
      /**
       * <code>required fixed32 port = 2;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required fixed32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required fixed32 port = 2;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000002;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required fixed32 port = 2;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.tsixi.mars.cluster.pb.Address)
    }

    static {
      defaultInstance = new Address(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tsixi.mars.cluster.pb.Address)
  }

  public interface SessionEnterOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional fixed32 message_type = 1 [default = 9];
    /**
     * <code>optional fixed32 message_type = 1 [default = 9];</code>
     */
    boolean hasMessageType();
    /**
     * <code>optional fixed32 message_type = 1 [default = 9];</code>
     */
    int getMessageType();

    // optional fixed32 cmd = 2 [default = 1];
    /**
     * <code>optional fixed32 cmd = 2 [default = 1];</code>
     */
    boolean hasCmd();
    /**
     * <code>optional fixed32 cmd = 2 [default = 1];</code>
     */
    int getCmd();

    // required string sessionId = 3;
    /**
     * <code>required string sessionId = 3;</code>
     */
    boolean hasSessionId();
    /**
     * <code>required string sessionId = 3;</code>
     */
    java.lang.String getSessionId();
    /**
     * <code>required string sessionId = 3;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();

    // required .com.tsixi.mars.cluster.pb.Address address = 4;
    /**
     * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
     */
    boolean hasAddress();
    /**
     * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
     */
    SessionMessage.Address getAddress();
    /**
     * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
     */
    SessionMessage.AddressOrBuilder getAddressOrBuilder();
  }
  /**
   * Protobuf type {@code com.tsixi.mars.cluster.pb.SessionEnter}
   */
  public static final class SessionEnter extends
      com.google.protobuf.GeneratedMessage
      implements SessionEnterOrBuilder {
    // Use SessionEnter.newBuilder() to construct.
    private SessionEnter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SessionEnter(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SessionEnter defaultInstance;
    public static SessionEnter getDefaultInstance() {
      return defaultInstance;
    }

    public SessionEnter getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SessionEnter(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              messageType_ = input.readFixed32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              cmd_ = input.readFixed32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              sessionId_ = input.readBytes();
              break;
            }
            case 34: {
              SessionMessage.Address.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(SessionMessage.Address.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_SessionEnter_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_SessionEnter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SessionMessage.SessionEnter.class, SessionMessage.SessionEnter.Builder.class);
    }

    public static com.google.protobuf.Parser<SessionEnter> PARSER =
        new com.google.protobuf.AbstractParser<SessionEnter>() {
      public SessionEnter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SessionEnter(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SessionEnter> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional fixed32 message_type = 1 [default = 9];
    public static final int MESSAGE_TYPE_FIELD_NUMBER = 1;
    private int messageType_;
    /**
     * <code>optional fixed32 message_type = 1 [default = 9];</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional fixed32 message_type = 1 [default = 9];</code>
     */
    public int getMessageType() {
      return messageType_;
    }

    // optional fixed32 cmd = 2 [default = 1];
    public static final int CMD_FIELD_NUMBER = 2;
    private int cmd_;
    /**
     * <code>optional fixed32 cmd = 2 [default = 1];</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional fixed32 cmd = 2 [default = 1];</code>
     */
    public int getCmd() {
      return cmd_;
    }

    // required string sessionId = 3;
    public static final int SESSIONID_FIELD_NUMBER = 3;
    private java.lang.Object sessionId_;
    /**
     * <code>required string sessionId = 3;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string sessionId = 3;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sessionId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required .com.tsixi.mars.cluster.pb.Address address = 4;
    public static final int ADDRESS_FIELD_NUMBER = 4;
    private SessionMessage.Address address_;
    /**
     * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
     */
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
     */
    public SessionMessage.Address getAddress() {
      return address_;
    }
    /**
     * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
     */
    public SessionMessage.AddressOrBuilder getAddressOrBuilder() {
      return address_;
    }

    private void initFields() {
      messageType_ = 9;
      cmd_ = 1;
      sessionId_ = "";
      address_ = SessionMessage.Address.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getAddress().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed32(1, messageType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed32(2, cmd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, address_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, messageType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, cmd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSessionIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, address_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SessionMessage.SessionEnter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SessionMessage.SessionEnter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SessionMessage.SessionEnter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SessionMessage.SessionEnter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SessionMessage.SessionEnter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SessionMessage.SessionEnter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SessionMessage.SessionEnter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SessionMessage.SessionEnter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SessionMessage.SessionEnter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SessionMessage.SessionEnter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SessionMessage.SessionEnter prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tsixi.mars.cluster.pb.SessionEnter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SessionMessage.SessionEnterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_SessionEnter_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_SessionEnter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SessionMessage.SessionEnter.class, SessionMessage.SessionEnter.Builder.class);
      }

      // Construct using SessionMessage.SessionEnter.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAddressFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageType_ = 9;
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 1;
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        if (addressBuilder_ == null) {
          address_ = SessionMessage.Address.getDefaultInstance();
        } else {
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_SessionEnter_descriptor;
      }

      public SessionMessage.SessionEnter getDefaultInstanceForType() {
        return SessionMessage.SessionEnter.getDefaultInstance();
      }

      public SessionMessage.SessionEnter build() {
        SessionMessage.SessionEnter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SessionMessage.SessionEnter buildPartial() {
        SessionMessage.SessionEnter result = new SessionMessage.SessionEnter(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessionId_ = sessionId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SessionMessage.SessionEnter) {
          return mergeFrom((SessionMessage.SessionEnter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SessionMessage.SessionEnter other) {
        if (other == SessionMessage.SessionEnter.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasSessionId()) {
          bitField0_ |= 0x00000004;
          sessionId_ = other.sessionId_;
          onChanged();
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSessionId()) {
          
          return false;
        }
        if (!hasAddress()) {
          
          return false;
        }
        if (!getAddress().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SessionMessage.SessionEnter parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SessionMessage.SessionEnter) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional fixed32 message_type = 1 [default = 9];
      private int messageType_ = 9;
      /**
       * <code>optional fixed32 message_type = 1 [default = 9];</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional fixed32 message_type = 1 [default = 9];</code>
       */
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <code>optional fixed32 message_type = 1 [default = 9];</code>
       */
      public Builder setMessageType(int value) {
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed32 message_type = 1 [default = 9];</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = 9;
        onChanged();
        return this;
      }

      // optional fixed32 cmd = 2 [default = 1];
      private int cmd_ = 1;
      /**
       * <code>optional fixed32 cmd = 2 [default = 1];</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional fixed32 cmd = 2 [default = 1];</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>optional fixed32 cmd = 2 [default = 1];</code>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000002;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed32 cmd = 2 [default = 1];</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = 1;
        onChanged();
        return this;
      }

      // required string sessionId = 3;
      private java.lang.Object sessionId_ = "";
      /**
       * <code>required string sessionId = 3;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionId_ = value;
        onChanged();
        return this;
      }

      // required .com.tsixi.mars.cluster.pb.Address address = 4;
      private SessionMessage.Address address_ = SessionMessage.Address.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          SessionMessage.Address, SessionMessage.Address.Builder, SessionMessage.AddressOrBuilder> addressBuilder_;
      /**
       * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
       */
      public SessionMessage.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
       */
      public Builder setAddress(SessionMessage.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
       */
      public Builder setAddress(
          SessionMessage.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
       */
      public Builder mergeAddress(SessionMessage.Address value) {
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              address_ != SessionMessage.Address.getDefaultInstance()) {
            address_ =
              SessionMessage.Address.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = SessionMessage.Address.getDefaultInstance();
          onChanged();
        } else {
          addressBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
       */
      public SessionMessage.Address.Builder getAddressBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
       */
      public SessionMessage.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_;
        }
      }
      /**
       * <code>required .com.tsixi.mars.cluster.pb.Address address = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          SessionMessage.Address, SessionMessage.Address.Builder, SessionMessage.AddressOrBuilder>
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              SessionMessage.Address, SessionMessage.Address.Builder, SessionMessage.AddressOrBuilder>(
                  address_,
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.tsixi.mars.cluster.pb.SessionEnter)
    }

    static {
      defaultInstance = new SessionEnter(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tsixi.mars.cluster.pb.SessionEnter)
  }

  public interface SessionQuitOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional fixed32 message_type = 1 [default = 9];
    /**
     * <code>optional fixed32 message_type = 1 [default = 9];</code>
     */
    boolean hasMessageType();
    /**
     * <code>optional fixed32 message_type = 1 [default = 9];</code>
     */
    int getMessageType();

    // optional fixed32 cmd = 2 [default = 2];
    /**
     * <code>optional fixed32 cmd = 2 [default = 2];</code>
     */
    boolean hasCmd();
    /**
     * <code>optional fixed32 cmd = 2 [default = 2];</code>
     */
    int getCmd();

    // required string sessionId = 3;
    /**
     * <code>required string sessionId = 3;</code>
     */
    boolean hasSessionId();
    /**
     * <code>required string sessionId = 3;</code>
     */
    java.lang.String getSessionId();
    /**
     * <code>required string sessionId = 3;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();
  }
  /**
   * Protobuf type {@code com.tsixi.mars.cluster.pb.SessionQuit}
   */
  public static final class SessionQuit extends
      com.google.protobuf.GeneratedMessage
      implements SessionQuitOrBuilder {
    // Use SessionQuit.newBuilder() to construct.
    private SessionQuit(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SessionQuit(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SessionQuit defaultInstance;
    public static SessionQuit getDefaultInstance() {
      return defaultInstance;
    }

    public SessionQuit getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SessionQuit(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 13: {
              bitField0_ |= 0x00000001;
              messageType_ = input.readFixed32();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              cmd_ = input.readFixed32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              sessionId_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_SessionQuit_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_SessionQuit_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              SessionMessage.SessionQuit.class, SessionMessage.SessionQuit.Builder.class);
    }

    public static com.google.protobuf.Parser<SessionQuit> PARSER =
        new com.google.protobuf.AbstractParser<SessionQuit>() {
      public SessionQuit parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SessionQuit(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SessionQuit> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional fixed32 message_type = 1 [default = 9];
    public static final int MESSAGE_TYPE_FIELD_NUMBER = 1;
    private int messageType_;
    /**
     * <code>optional fixed32 message_type = 1 [default = 9];</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional fixed32 message_type = 1 [default = 9];</code>
     */
    public int getMessageType() {
      return messageType_;
    }

    // optional fixed32 cmd = 2 [default = 2];
    public static final int CMD_FIELD_NUMBER = 2;
    private int cmd_;
    /**
     * <code>optional fixed32 cmd = 2 [default = 2];</code>
     */
    public boolean hasCmd() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional fixed32 cmd = 2 [default = 2];</code>
     */
    public int getCmd() {
      return cmd_;
    }

    // required string sessionId = 3;
    public static final int SESSIONID_FIELD_NUMBER = 3;
    private java.lang.Object sessionId_;
    /**
     * <code>required string sessionId = 3;</code>
     */
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string sessionId = 3;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sessionId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sessionId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      messageType_ = 9;
      cmd_ = 2;
      sessionId_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasSessionId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFixed32(1, messageType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed32(2, cmd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSessionIdBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, messageType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, cmd_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSessionIdBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static SessionMessage.SessionQuit parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SessionMessage.SessionQuit parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SessionMessage.SessionQuit parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static SessionMessage.SessionQuit parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static SessionMessage.SessionQuit parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SessionMessage.SessionQuit parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static SessionMessage.SessionQuit parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static SessionMessage.SessionQuit parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static SessionMessage.SessionQuit parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static SessionMessage.SessionQuit parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(SessionMessage.SessionQuit prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.tsixi.mars.cluster.pb.SessionQuit}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements SessionMessage.SessionQuitOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_SessionQuit_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_SessionQuit_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                SessionMessage.SessionQuit.class, SessionMessage.SessionQuit.Builder.class);
      }

      // Construct using SessionMessage.SessionQuit.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageType_ = 9;
        bitField0_ = (bitField0_ & ~0x00000001);
        cmd_ = 2;
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return SessionMessage.internal_static_com_tsixi_mars_cluster_pb_SessionQuit_descriptor;
      }

      public SessionMessage.SessionQuit getDefaultInstanceForType() {
        return SessionMessage.SessionQuit.getDefaultInstance();
      }

      public SessionMessage.SessionQuit build() {
        SessionMessage.SessionQuit result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public SessionMessage.SessionQuit buildPartial() {
        SessionMessage.SessionQuit result = new SessionMessage.SessionQuit(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cmd_ = cmd_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessionId_ = sessionId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof SessionMessage.SessionQuit) {
          return mergeFrom((SessionMessage.SessionQuit)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(SessionMessage.SessionQuit other) {
        if (other == SessionMessage.SessionQuit.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        if (other.hasCmd()) {
          setCmd(other.getCmd());
        }
        if (other.hasSessionId()) {
          bitField0_ |= 0x00000004;
          sessionId_ = other.sessionId_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSessionId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        SessionMessage.SessionQuit parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (SessionMessage.SessionQuit) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional fixed32 message_type = 1 [default = 9];
      private int messageType_ = 9;
      /**
       * <code>optional fixed32 message_type = 1 [default = 9];</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional fixed32 message_type = 1 [default = 9];</code>
       */
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <code>optional fixed32 message_type = 1 [default = 9];</code>
       */
      public Builder setMessageType(int value) {
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed32 message_type = 1 [default = 9];</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = 9;
        onChanged();
        return this;
      }

      // optional fixed32 cmd = 2 [default = 2];
      private int cmd_ = 2;
      /**
       * <code>optional fixed32 cmd = 2 [default = 2];</code>
       */
      public boolean hasCmd() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional fixed32 cmd = 2 [default = 2];</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <code>optional fixed32 cmd = 2 [default = 2];</code>
       */
      public Builder setCmd(int value) {
        bitField0_ |= 0x00000002;
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional fixed32 cmd = 2 [default = 2];</code>
       */
      public Builder clearCmd() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cmd_ = 2;
        onChanged();
        return this;
      }

      // required string sessionId = 3;
      private java.lang.Object sessionId_ = "";
      /**
       * <code>required string sessionId = 3;</code>
       */
      public boolean hasSessionId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public Builder clearSessionId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>required string sessionId = 3;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sessionId_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.tsixi.mars.cluster.pb.SessionQuit)
    }

    static {
      defaultInstance = new SessionQuit(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.tsixi.mars.cluster.pb.SessionQuit)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsixi_mars_cluster_pb_Address_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tsixi_mars_cluster_pb_Address_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsixi_mars_cluster_pb_SessionEnter_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tsixi_mars_cluster_pb_SessionEnter_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_tsixi_mars_cluster_pb_SessionQuit_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_tsixi_mars_cluster_pb_SessionQuit_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033proto/session-message.proto\022\031com.tsixi" +
      ".mars.cluster.pb\"%\n\007Address\022\014\n\004host\030\001 \002(" +
      "\t\022\014\n\004port\030\002 \002(\007\"\177\n\014SessionEnter\022\027\n\014messa" +
      "ge_type\030\001 \001(\007:\0019\022\016\n\003cmd\030\002 \001(\007:\0011\022\021\n\tsess" +
      "ionId\030\003 \002(\t\0223\n\007address\030\004 \002(\0132\".com.tsixi" +
      ".mars.cluster.pb.Address\"I\n\013SessionQuit\022" +
      "\027\n\014message_type\030\001 \001(\007:\0019\022\016\n\003cmd\030\002 \001(\007:\0012" +
      "\022\021\n\tsessionId\030\003 \002(\tB\020B\016SessionMessage"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_tsixi_mars_cluster_pb_Address_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_tsixi_mars_cluster_pb_Address_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_tsixi_mars_cluster_pb_Address_descriptor,
              new java.lang.String[] { "Host", "Port", });
          internal_static_com_tsixi_mars_cluster_pb_SessionEnter_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_tsixi_mars_cluster_pb_SessionEnter_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_tsixi_mars_cluster_pb_SessionEnter_descriptor,
              new java.lang.String[] { "MessageType", "Cmd", "SessionId", "Address", });
          internal_static_com_tsixi_mars_cluster_pb_SessionQuit_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_tsixi_mars_cluster_pb_SessionQuit_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_tsixi_mars_cluster_pb_SessionQuit_descriptor,
              new java.lang.String[] { "MessageType", "Cmd", "SessionId", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
